a = input ('digite algo')
print ('o tipo primitivo desse valor é',type(a))
print('só tem espaço',a.isspace())
print('isso é numerico?', a.isnumeric())
print('isso é alfabetico?', a.isalpha())
print('isso é alfanumerico?', a.isalnum())
print('esta em maiuscula?', a.isupper())
print('esta em minuscula?', a.islower() )
print('esta capitalizada?', a.istitle() )
