a = input('digite algo:')
print('o tipo primitivo é', type(a))
print('só tem espaços?', a.isspace())
print('é um número ?', a.isnumeric())
print('é ema palavra ?', a.isalpha())
print('é uma palavra e um número ?', a.isalnum())
print('esta em maiusculas ?', a.isupper())
print('esta em miniscusla ?', a.islower())
print('esta capitalizada ?', a.istitle())
